#!/bin/sh -x

# set -ue: treat unset variables as an error; exit on error
set -ue

# use absolute paths instead of relative
top_srcdir=`cd $top_srcdir; pwd`

cd $top_srcdir/test

echo exit sql.sqlcode | sqlplus -s $USERID @oradumper_test.sql

cd -
